services:
  # ----------------------------------------
  # BANCO DE DADOS (MySQL)
  # ----------------------------------------
  db:
    image: mysql:8.0
    container_name: autocatira_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # ports:
    #   - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - autocatira_network

  # ----------------------------------------
  # BACK-END (API Node.js)
  # ----------------------------------------
  backend:
    build: ./backend
    container_name: autocatira_backend
    restart: always
    # ports:
    #   - "3333:3333"
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - autocatira_network

  # ----------------------------------------
  # FRONT-END (Interface React)
  # ----------------------------------------
  frontend:
    build: ./frontend
    container_name: autocatira_frontend
    restart: always
    # ports:
    #  - "3000:3000"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend
    networks:
      - autocatira_network

  # ----------------------------------------
  # NGINX
  # ----------------------------------------
  nginx:
    image: nginx:alpine
    container_name: autocatira_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend
    networks:
      - autocatira_network
# ----------------------------------------
# VOLUMES E REDES
# ----------------------------------------
volumes:
  db_data:

networks:
  autocatira_network:
    driver: bridge
